---
abstract: 'assert reference counts on objects'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::Builder::Tester: '0'
  Test::More: '0.88'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Refcount
provides:
  Test::Refcount:
    file: lib/Test/Refcount.pm
    version: '0.10'
recommends:
  Devel::MAT: '0.04'
requires:
  B: '0'
  Scalar::Util: '0'
  Test::Builder: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.10'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
